# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nawin Ngampoopun"
resume_title:                   "PhD Student in Solar Physics"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nawin.ngampoopun.21@ucl.ac.uk"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+44 7824 421819"
resume_contact_address:         "Mullard Space Science Laboratory, Holmbury St Mary, Dorking, RH5 6NT, UK"

resume_header_contact_info:     "Mullard Space Science Laboratory, Holmbury St Mary, Dorking, RH5 6NT, UK • nawin.ngampoopun.21@ucl.ac.uk "
display_header_contact_info:    "true"

resume_header_intro: "<p> I am a postgraduate research students in Solar Physics. My main research interests are 'Coronal Holes' and solar wind streams emanating from them, which have significant effect on the Earth in form of space weather. Specifically, I focus on the evolutionary aspect of coronal holes and how it may link to the formation of solar wind </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nawinnova"
  resume_twitter_url:           "http://twitter.com/nawin_nga"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/nawinnova.ngampoopun"
  resume_linkedin_url:          "https://www.linkedin.com/in/nawin-ngampoopun-3a57a21a4"
  resume_instagram_url:         "https://www.instagram.com/nawinnova/"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
